version: '3.4'

services:
  dotnetcoreconsoleapi:
    image: dotnetcoreconsoleapi:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dotnetcoreconsoleapi$
    volumes:
      - D:\Repo\git\dotnet\DotNetCoreConsoleAPI:/app
      - C:\Users\Pravin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_dotnetcoreconsoleapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dotnetcoreconsoleapi$ "
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
